---
version: 2
project_name: garmin-exporter

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: garmin-exporter
    binary: garmin-exporter
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/prometheus/common/version.Version={{ .Version }}
      - -X github.com/prometheus/common/version.Revision={{ .Commit }}
      - -X github.com/prometheus/common/version.Branch={{ .Branch }}
      - -X github.com/prometheus/common/version.BuildDate={{ .Date }}
      - -X github.com/prometheus/common/version.BuildUser=goreleaser

archives:
  - id: tarball
    formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

dockers:
  - id: amd64
    image_templates:
      - "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}-amd64"
      - "docker.io/barnesbiz/garmin-exporter:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"
  - id: arm64
    image_templates:
      - "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}-arm64"
      - "docker.io/barnesbiz/garmin-exporter:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile.release
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .Commit }}"

docker_manifests:
  - name_template: "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}"
    image_templates:
      - "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}-amd64"
      - "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}-arm64"
  - name_template: "ghcr.io/barnes-c/garmin-exporter:latest"
    image_templates:
      - "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}-amd64"
      - "ghcr.io/barnes-c/garmin-exporter:{{ .Version }}-arm64"
  - name_template: "docker.io/barnesbiz/garmin-exporter:{{ .Version }}"
    image_templates:
      - "docker.io/barnesbiz/garmin-exporter:{{ .Version }}-amd64"
      - "docker.io/barnesbiz/garmin-exporter:{{ .Version }}-arm64"
  - name_template: "docker.io/barnesbiz/garmin-exporter:latest"
    image_templates:
      - "docker.io/barnesbiz/garmin-exporter:{{ .Version }}-amd64"
      - "docker.io/barnesbiz/garmin-exporter:{{ .Version }}-arm64"

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - --output-signature=${signature}
      - --output-certificate=${certificate}
      - --yes
      - ${artifact}
    artifacts: checksum

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
      - sign
      - --oidc-issuer=https://token.actions.githubusercontent.com
      - --yes
      - ${artifact}

release:
  github:
    owner: barnes-c
    name: garmin-exporter
  draft: true
  prerelease: auto
