services:
  garmin_exporter:
    image: ghcr.io/barnes-c/garmin_exporter:latest
    ports:
      - "10043:10043"
    environment:
      GARMIN_USERNAME: ${GARMIN_USERNAME}
      GARMIN_PASSWORD: ${GARMIN_PASSWORD}
    volumes:
      - garmin_data:/data
    command:
      - --garmin.token-file=/data/garmin_token.json
    restart: unless-stopped

volumes:
  garmin_data:
