---
name: goreleaser
on:
  pull_request:
    paths:
      - "**/*goreleaser*.yml"
      - "Dockerfile.release"
  push:
    branches: [main, master]
    paths:
      - "**/*goreleaser*.yml"
      - "Dockerfile.release"

permissions:
  contents: read

jobs:
  check:
    name: Validate .goreleaser.yml
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          distribution: goreleaser
          version: "~> v2"
          args: check --config .github/.goreleaser.yml
